spring:
  application:
    name: gateway

server:
  port: 8080
  
    
eureka:
  instance:
    preferIpAddress: true
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka/
    fetchRegistry: true
    registerWithEureka: true

zuul:
  sensitive-headers: Cookie

security:
  oauth2:
    resource:
      userInfoUri: http://localhost:8083/usuario
    client:
      resource-ids: resources
      